trigger:
- main

variables:
  imageName: 'flask-aks-app'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - checkout: self
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: khushiacr321.azurecr.io/$(imageName)  
        dockerfile: '**/Dockerfile'
        containerRegistry: 'KhushiACRConnection'
        tags: latest
        buildContext: .
        arguments: '--platform linux/amd64'


- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: Deploy Deployment.yaml
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-subscription-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: manifests/deployment.yaml

    - task: Kubernetes@1
      displayName: Deploy Service.yaml
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'azure-subscription-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: manifests/service.yaml
