trigger:
- main

variables:
  imageName: 'flask-aks-app'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - checkout: self

    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'KhushiACRConnection'
        tags: 'latest'

- stage: Deploy
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'azure-subscription-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: manifests/deployment.yaml

    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'azure-subscription-connection'
        azureResourceGroup: 'flask-rg'
        kubernetesCluster: 'flask-aks'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: manifests/service.yaml
